### ISSUE TITLE
[Roadmap] FlashInfer v0.0.1 release checklist

### ISSUE THREAD

**Issue by yzh119** [flashinfer-ai/flashinfer#11]
# Checklist
Ranked by priority (from high to low):
- [x] Docstring for C++ APIs.
- [x] PyTorch APIs and PyPI package.
- [x] Thread local buffer manager for cooperative kernels.
  - [x] TVM Wrapper
  - <del> [ ] PyTorch API </del> (Do not expose batch APIs for pytorch)
- [x] Initial support Customized Page Table Style (storing indices or pointer)
- [x] Shared Prefix Parallel Decoding
- [x] Accelerate batched prefill kernel.
- [x] Accelerate sin/cos in rope computation.
- <del> [ ] Sliding Window Attention (SWA). </del> (postponed to v0.2)
