### ISSUE TITLE
[LoRA] Roadmap of LoRA operators

### ISSUE THREAD

**Issue by yzh119** [flashinfer-ai/flashinfer#199]
1. [ ] Reducing the latency of LoRA operators (per lorax feedback, lora operators introduce ~20% overhead).
2. [ ] Numerical issue of LoRA operators for large batch size.
3. [ ] Using fp8 tensor cores for LoRA operators.

**Comment by tgaddair** [comment]
Thanks for filing this issue @yzh119! Happy to help out in any way I can.
