### ISSUE TITLE
[Tracking Issue] Documentation and Examples

### ISSUE THREAD

**Issue by yzh119** [flashinfer-ai/flashinfer#67]
- [ ] Blog posts to introduce the features and principles
- [ ] Update README file.
- [ ] Documentations for API use.
- [ ] Minimal example of deploying LLM with flashinfer APIs (e.g. through gpt-fast).

**Comment by sricketts** [comment]
> Minimal example of deploying LLM with flashinfer APIs (e.g. through gpt-fast).

This is now tracked with #1811. Closing this issue as done.
